### ISSUE TITLE
Paid Entries Not Marked As Paid

### ISSUE THREAD

**Issue by bwestfall03** [geoffhumphrey/brewcompetitiononlineentry#879]
It seems as if our entries are getting paid through PayPal but they are not marked as paid on the competition website. We did a test and went through the process and did click the link in PayPal to return to the comp site but the entry was not marked as paid. We do have the IPN setup.

**Comment by bwestfall03** [comment]
I am getting a message of RECEIVER EMAIL MISMATCH in the payment management screen. I have checked on the url's and they all look good. We are still not marking paid entries, what could I be missing?

**Comment by geoffhumphrey** [comment]
In the ppv.php file, RECEIVER EMAIL MISMATCH is a default state in the code unless the boolean $receiver_email_found is set to TRUE. I suspect it may have to do with the sterilizer() function that scrubs $POST_ variables mangling the receiver email address in some unexpected way, thus creating a mismatch. Try this, in the ppv.php file, change the following line:
```
$data['receiver_email'] = sterilize($_POST['receiver_email']);
```
To:
```
$data['receiver_email'] = filter_var($_POST['receiver_email'],FILTER_SANITIZE_EMAIL);
```
This may help. There have been some reported issues with the sterilize() function mucking things up. I'll be looking into it more for the upcoming release. Try this first.

In fact, since the data is being posted directly from PayPal, and therefore assumed not to be malicious, you could probably remove all sanitize() function calls from the variable declarations in the block and replace them with php's built-in FILTER_SANITIZE_STRING function:
```
$data['payment_status'] = filter_var($_POST['payment_status'],FILTER_SANITIZE_STRING);
$data['item_name'] = filter_var($_POST['item_name'],FILTER_SANITIZE_STRING);
$data['item_number'] = filter_var($_POST['item_number'],FILTER_SANITIZE_STRING);
$data['payment_status'] = filter_var($_POST['payment_status'],FILTER_SANITIZE_STRING);
$data['payment_amount'] = filter_var($_POST['mc_gross'],FILTER_SANITIZE_STRING);
$data['payment_currency'] = filter_var($_POST['mc_currency'],FILTER_SANITIZE_STRING);
$data['txn_id'] = filter_var($_POST['txn_id'],FILTER_SANITIZE_STRING);
$data['receiver_email'] = filter_var($_POST['receiver_email'],FILTER_SANITIZE_EMAIL);
$data['first_name'] = filter_var($_POST['first_name'],FILTER_SANITIZE_STRING);
$data['last_name'] = filter_var($_POST['last_name'],FILTER_SANITIZE_STRING);
$data['payer_email'] = filter_var($_POST['payer_email'],FILTER_SANITIZE_EMAIL);
$data['custom'] = filter_var($_POST['custom'],FILTER_SANITIZE_STRING);
```

**Comment by bwestfall03** [comment]
Geoff, can I get to the ppv.php file if you are hosting it?

**Comment by geoffhumphrey** [comment]
Ah, I didn't realize you were on a hosted account. Let me know what your installation's URL is and I'll make the changes.

**Comment by bwestfall03** [comment]
Sorry Geoff,

http://brewoff.brewcomp.com/

**Comment by geoffhumphrey** [comment]
No problem. It's hard for me to keep everyone whose involved with a hosted site straight, it appears. I've updated your installation with the new code. Let me know if you have any further problems. 

I just tested it on my test installation and it worked as expected.

**Comment by bwestfall03** [comment]
I just ran a test through it and it still does not mark the entry as paid.

![2018-02-01_153843](https://user-images.githubusercontent.com/35609538/35704724-06ad37b8-0766-11e8-8c79-80ab6489b3ec.png)
![2018-02-01_153653](https://user-images.githubusercontent.com/35609538/35704695-f0884e28-0765-11e8-920d-3073f5c16fbf.png)

**Comment by geoffhumphrey** [comment]
You may need to refresh or access your entry list to verify. Is it still not marked?

**Comment by geoffhumphrey** [comment]
Couple of things to check too. From the ppv.php file (since you don't have access to it):
```
To implement:
1. Users will need to enable Auto Return for Website Payments in PayPal to $base_url."index.php?section=pay&msg=10";
	-- Must have a business account
	-- Login > Profile > My Selling Tools > Website Preferences
	
2. Users will need to enable Instant Payment Notification (IPN)
	-- Must have a business account
	-- Login > Profile > My Selling Tools > Instant payment notifications
	-- Notification URL should be $base_url."ppv.php";
```
Also, check http://brewcompetition.com/paypal-ipn as well.

**Comment by bwestfall03** [comment]
Here are screenshots of the paypal settings. I believe they are correct.

![2018-02-02_075042](https://user-images.githubusercontent.com/35609538/35736536-00aa7776-07ee-11e8-95b5-73805cad4a22.png)

![2018-02-02_074959](https://user-images.githubusercontent.com/35609538/35736531-fdc8846c-07ed-11e8-9fd2-aa6239513bc3.png)

**Comment by geoffhumphrey** [comment]
Hrm. My test installation is on the same server as yours, so I believe we can rule out a server-related issue. I tested the function on your installation using PayPal's [IPN Simulator](https://developer.paypal.com/developer/ipnSimulator/) and the "handshake wasn't able to be verfied." 

So, I again replaced your ppv.php file with one that was updated with the changes I detailed above, tested it with the simulator, and the "IPN was sent and the handshake verified" (see below). So, I can conclude that there was still a problem with the ppv.php script on your installation.

![2018-02-02_9-18-08](https://user-images.githubusercontent.com/5216502/35743342-93143d98-07fa-11e8-8511-c1fdbbc8ab75.jpg)

Hopefully, things should be working properly now... Apologies for any inconvenience.

**Comment by bwestfall03** [comment]
Thanks again for looking into it Geoff. I'll let you know if we find any issues.

**Comment by bwestfall03** [comment]
Sorry to say Geoff the entries are still not getting marked as paid. We had a few entries pay this weekend and the competition site still had them as unpaid.

**Comment by geoffhumphrey** [comment]
Hrm.  OK. Last resort... On your PayPal seller tools dashboard, change your IPN notification URL to be ```http://test.brewcomp.com/ppv.php``` - truthfully, I'm stumped on this one. Another comp with over 500 entries on the same server used IPN and had no issues.

**Comment by geoffhumphrey** [comment]
Barring that, simply disable accepting payment via IPN in Website Preferences to go back to the "old way" of utilizing PayPal payments. At least that way, you won't have any mystery paid entries.

**Comment by bwestfall03** [comment]
URL changed.

![2018-02-05_102820](https://user-images.githubusercontent.com/35609538/35815998-64e0c86c-0a5f-11e8-9a8e-705cc5aea364.png)

**Comment by geoffhumphrey** [comment]
Whoops. Nevermind on changing the IPN notification URL. I just realized that the script needs your installation's DB credentials, name, etc. If you use the test.brewcomp.com/ppv.php file, it will not update your installation's DB because it's not pointing to the correct DB tables.

Use this URL: ```http://test.brewcomp.com/ppv-brewoff.php```

**Comment by bwestfall03** [comment]
I have changed the URL

**Comment by bwestfall03** [comment]
We had a few entries pay but still not marking it in the website.

**Comment by geoffhumphrey** [comment]
At this point I would update your preferences to utilize the "old" way of accepting PayPal payments. I'll keep investigating, but in the interim and for sanity's sake, my advice would be to make the change.
