### ISSUE TITLE
2.1.14 - Required Info character limit should automatically reduce to 65 for categories with Optional Info

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#979]
Version: 2.1.13
Installation URL: brewslam.gtabrews.ca
Is your installation hosted on brewcompetition.com or brewcomp.com? Self Hosted

Description of Issue:

Following on from this comment on #876 :
https://github.com/geoffhumphrey/brewcompetitiononlineentry/issues/876#issuecomment-406646976

I think that the character limit should automatically adjust down to 65 for categories that allow for Optional Info. I would love to be able to increase the character limit, since most specialty categories only have "Required Info", but I'm wary of the hidden 68 character truncation you mentioned.

Would it be possible to have a built in check that reduces the character limit for Required Info down to 65 in categories with Optional Info, otherwise it uses whatever number you put in?

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by ercousin** [comment]
Adding onto this, it seems that 65 is still not a safe number of use. Our competition saw several entries with descriptions of less than 65 characters still get truncated on the sticker

Eg. 23F with 55 characters
1yr lambic aged on 14lbs of fresh Ontario sour cherries
![image](https://user-images.githubusercontent.com/1551339/48392113-ce66c980-e6d7-11e8-8876-46e742185801.png)
![image](https://user-images.githubusercontent.com/1551339/48391985-2a7d1e00-e6d7-11e8-94cb-39570b6c209b.png)

Eg. 29A with 65 characters
Berliner Weisse w blueberries, soured w lacto, fermented w Kölsch
![image](https://user-images.githubusercontent.com/1551339/48392079-a5463900-e6d7-11e8-8f9f-1d9881f84f85.png)
![image](https://user-images.githubusercontent.com/1551339/48392083-ab3c1a00-e6d7-11e8-929d-3f946c69abfa.png)

**Comment by ercousin** [comment]
@geoffhumphrey Did you have a chance to look at this? I saw you were going to fix it in 2.1.15, but it got dropped.

**Comment by geoffhumphrey** [comment]
@ercousin, I believe [this commit](https://github.com/geoffhumphrey/brewcompetitiononlineentry/commit/bb741ebc850c547783b9bf2d54e3b35abeba9f96) has fixed the issue. However, regarding the second example you provided (I can't believe it took me this long to figure it out), the script was thrown off by the umlaut in Kölsch because vanilla FPDF does not support UTF-8 characters. This commit will convert UTF-8 characters and/or simply scrub them out.

In the future, I'll look for a way to support UTF-8 encoding with FPDF. There are some extensions that are worth investigating. For now, this should fix the issue reported here.

**Comment by ercousin** [comment]
Hi @geoffhumphrey ,

I tried the latest master version and I do see the ö getting stripped out, but my first scenario still isn't fixed.

I re-created the original two scenarios using the new BCOEM version:

### Scenario 1 (not fixed):
Eg. 23F with 55 characters
1yr lambic aged on 14lbs of fresh Ontario sour cherries

Entry:
![image](https://user-images.githubusercontent.com/1551339/65077786-aab08780-d969-11e9-87e2-eb1b8ceed464.png)

Bottle Label:
![image](https://user-images.githubusercontent.com/1551339/65077681-72a94480-d969-11e9-91f2-af757661f91a.png)

### Scenario 2 (sort of fixed):
Eg. 29A with 65 characters
Berliner Weisse w blueberries, soured w lacto, fermented w Kölsch

Entry:
![image](https://user-images.githubusercontent.com/1551339/65077808-b9973a00-d969-11e9-889b-4395e933af1c.png)

Bottle Label:
![image](https://user-images.githubusercontent.com/1551339/65077843-cb78dd00-d969-11e9-9a81-19c8c0d5911e.png)

Can you take another look?

**Comment by geoffhumphrey** [comment]
@ercousin, I just pushed [a commit](https://github.com/geoffhumphrey/brewcompetitiononlineentry/commit/30b853fa6b599b3f078ab7e28ab80388dbaaf95b) that should fix all the issues reported here.

Give it a whirl and let me know if it works for you. If it's fixed, I guess the 427th time is a charm. 🥇

**Comment by ercousin** [comment]
Thanks @geoffhumphrey . I tried it out and the two "add on issues" from my 2nd comment in this issue are addressed.

![image](https://user-images.githubusercontent.com/1551339/65183811-3b529a80-da32-11e9-964c-b8dd7274b8e4.png)
![image](https://user-images.githubusercontent.com/1551339/65183833-49082000-da32-11e9-9b8f-1577c1926dd6.png)

**Comment by ercousin** [comment]
However the original request of "Required Info character limit should automatically reduce to 65 for categories with Optional Info" isn't fixed.

You may remember this comment:
https://github.com/geoffhumphrey/brewcompetitiononlineentry/issues/876

> If both are present, Required info and Optional Info will be truncated at 68 characters. If only Required Info is present, it will be truncated to 136 characters.

I'm just asking for this behavior to be enforced. If I set the character limit to 100, then it should be automatically adjusted down to 65 or so for categories that have optional or radio-button info. Then other categories that only have required info can benefit from extra characters.

Example 1)
![image](https://user-images.githubusercontent.com/1551339/65184246-1d396a00-da33-11e9-98ca-36b97d771f1c.png)
![image](https://user-images.githubusercontent.com/1551339/65184694-0e06ec00-da34-11e9-97be-fa6b77b6786f.png)


Example 2)
![image](https://user-images.githubusercontent.com/1551339/65184527-aa7cbe80-da33-11e9-9bdd-693535531f0a.png)
![image](https://user-images.githubusercontent.com/1551339/65184600-dbf58a00-da33-11e9-89fc-f38e19c43e7a.png)

**Comment by geoffhumphrey** [comment]
@ercousin - while I see the merit and convenience of dynamically limiting the possible characters for those particular styles that feature Optional Information, it would only apply to those competitions who use the Bottle Labels with Required Info. I'm reticent to enforce a rule for everyone that only will be useful to some.

I believe the best course of action here is for competition organizers set their text entry character limit to 65 or fewer if they wish to use the Bottle Labels with Required Info. This will ensure that both special ingredients and optional ingredients fit completely on the labels. I've added some help text in Website Preferences specifying this recommendation.
